# Generated by Django 3.1.7 on 2021-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACDMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=200)),
                ('patient_fullName', models.CharField(max_length=200)),
                ('patient_address', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=13)),
                ('patient_dateOfBirth', models.DateField()),
            ],
        ),
    ]
